### PR TITLE
Ppo patch

### LINKED ISSUE #38: Update PPO for better performance and closer alignment to sb3
Recently I played with the PPO model in `rl-ts` and found that the model was not very stable when playing the cartpole environment.

So I made a few changes and bug fixes with reference to the [PPO implementation](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/ppo/ppo.py) in sb3:

- Add mini-batch updates
- Unified policy and value function optimizers into one and combined loss from policy and value function
- Adjusted return formula according to sb3 [updated implementation](https://github.com/DLR-RM/stable-baselines3/pull/375)
- Updated a few formulas to match sb3 more closely
- Removed KL limit by default

These changes made the implementation (magenta) much more stable and reach optimal return earlier as compared to the original one(blue and black):

Screenshot 2023-03-16 at 5 40 08 PM

I checked the sb3 version and it also doesn't have max KL limit by default, though it does reach the max limit of `1.5 * 0.01` slower (epoch 7/8) than this implementation (1/2). So more work is needed to get closer match to sb3.

Let me know if you are interested in updating this library. I can open a PR to merge my updates.

### PR DESCRIPTION
**Pull request by paradite**
Fixes #38 

This PR introduces a number of features and bug fixes to make `rl-ts` PPO algorithm better and closer to the sb3 implementation:

- Add `Categorical` distribution and `MLPCategoricalActor`, and use it for environment with discrete action space
- Mini-batch updates of `batch_size` for `n_epochs` in each iteration, instead of fixed number of iterations per epoch
- Fix vf loss due to env terminated for reaching max episode step by bootstrapping reward for last step
- Update advantage formula according to [sb3 updated implementation](https://github.com/DLR-RM/stable-baselines3/pull/375)
- Combined optimizer and loss computation for pi and vf

Overall, the PPO implementation is more stable (lower KL and not hitting max KL limit) and performs better (able to reach optimal reward for cartpole within 50k steps).

The new performance compared against the old implementation:

Screenshot 2023-03-20 at 4 54 51 PM

### CODE REVIEW

**Comment by StoneT2000** [comment]
by the way @paradite would you be interested in maintaining this package moving forward? I don't think I'll have any time soon to maintain this. If so we can chat over discord/dm to figure this out.

**Comment by bmarotta** [comment]
@StoneT2000 : Are you ever going to accept this PR and publish a new package version on npm? I also noticed that PPO doesn't work if the ObservationSpace is a Dict.

**Comment by StoneT2000** [comment]
Sorry I haven't been able to look at this in forever, @paradite what is the best way perhaps to transfer ownership on npm?

**Comment by paradite** [comment]
> Sorry I haven't been able to look at this in forever, @paradite what is the best way perhaps to transfer ownership on npm?

Hi @StoneT2000. If you trust me enough, you can transfer the npm package to me: 

https://www.npmjs.com/~paradite

I do have 2FA on npm so it should be fine. I'll do some sanity test and publish a new version.

**Comment by StoneT2000** [comment]
I gave you maintainer access @paradite. I think it may also be better to transfer this repository over to you. It seems you have a repo called rl-ts already, you may need to remove it before i can transfer

**Comment by paradite** [comment]
> I gave you maintainer access @paradite. I think it may also be better to transfer this repository over to you. It seems you have a repo called rl-ts already, you may need to remove it before i can transfer

ok so i used to have a repo at https://github.com/paradite/rl-ts, but i have since renamed and transferred it to https://github.com/ai-simulator/rl-ts-ppo-patch (made it private repo now since it has lots of extra stuff).

now i only have https://github.com/paradite/rl-ts-public which is where this PR is coming from.

looks like GitHub is honoring the old repo name and not allowing transfer, in that case, maybe the next best alternative is for you to either transfer this repo into a public org like `rl-ts` and add me as a maintainer, or just add me to this personal repo of yours as a maintainer.

**Comment by StoneT2000** [comment]
I've invited you as a maintainer. Feel free to make your own org if you want as well!

**Comment by paradite** [comment]
Merging first and running tests to see if anything else needs to be changed before publishing a new npm package.

**Comment by paradite** [comment]
Two issues after merging:
- The deploy key for this repo is no long working, resulting in failed circleCI runs. (Might need help from @StoneT2000 to resolve)
- The test is failing for `VPG` after merging in PPO changes (I've changed the implementation in actor-critic so VPG is likely affected). I'll look into how to fix it. It's been a while since I worked on it so I need to spend some time digging.

Screenshot 2024-04-25 at 4 50 10 PM

**Comment by StoneT2000** [comment]
There are actually no deploy keys atm actually, i think you should be able to add them yourself

**Pull request merged**
